eureka:
  instance:
    hostname: /localhost
server:
  port: 8283
  context-path: /operate
spring:
  datasource:
    url: jdbc:mysql://192.168.10.109:3306/announcement?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: CarCredit2016
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 60
    maxActive: 20
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: truegene
    minEvictableIdleTimeMillis: 5000
    timeBetweenEvictionRunsMillis: 8000
endpoints:
  jmx:
    enabled: false
abc:
  cookieDomain: localhost
mybatis:
  mapper-locations: classpath:mybatis/*.xml