eureka:
  instance:
    hostname: /localhost
server:
  port: 8283
  servlet:
    context-path: /operate
spring:
  datasource:
    url: jdbc:mysql://192.168.10.110:3306/announcement?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: it
    password: Carcredit123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 60
    maxActive: 20
    validationQuery: SELECT 1
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: truegene
    minEvictableIdleTimeMillis: 5000
    timeBetweenEvictionRunsMillis: 8000
  redis:
    host: 192.168.10.109
    port: 6379
    password: carcredit123
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
endpoints:
  jmx:
    enabled: false
abc:
  cookieDomain: localhost
mybatis:
  mapper-locations: classpath:mybatis/*.xml